name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: salesforcecli/github-action@v1

      - name: Create auth file
        run: echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
        shell: bash

      - name: Authenticate to Salesforce org
        run: sfdx auth:sfdxurl:store --sfdxurlfile auth.txt --setdefaultusername --setalias DevOrg
        shell: bash

      - name: Deploy source to Salesforce
        run: sfdx force:source:deploy -p force-app -u DevOrg --wait 10 --verbose

